### ISSUE TITLE
Tesseract not found on macOS 10.12

### ISSUE THREAD

**Issue by L30coding** [Audiveris/audiveris-v5#3]
The gradle run tasks fails on macOS 10.12 with the following error message:
```
targetOS=macosx-x86_64
:git_build
:generateProgramId
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.audiveris.omr.Main.<clinit>(Main.java:64)
	at Audiveris.main(Audiveris.java:49)
Caused by: org.audiveris.omr.WellKnowns$InstallationException: Tesseract-OCR is not installed
	at org.audiveris.omr.WellKnowns.getOcrFolder(WellKnowns.java:446)
	at org.audiveris.omr.WellKnowns.<clinit>(WellKnowns.java:141)
	... 2 more
:run FAILED
```

Tesseract is installed using `brew install tesseract`. The installed version info is:
```
tesseract: stable 3.05.00 (bottled), HEAD
OCR (Optical Character Recognition) engine
https://github.com/tesseract-ocr/
/usr/local/Cellar/tesseract/3.05.00 (235 files, 1.2GB) *
  Built from source on 2017-03-04 at 10:10:01 with: --with-all-languages
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tesseract.rb
```

**Comment by maximumspatium** [comment]
You need to set the TESSDATA_PREFIX system variable correctly. It should point **to the parent directory** of the tessdata folder containing language data and preferences.

`export TESSDATA_PREFIX=/path/to/the/parent/dir/of/tessdata`
